### ISSUE TITLE
Customize extension

### ISSUE THREAD

**Issue by bennyn** [pakhuta/gzip-cli#1]
By default files saved by `gzip-cli` are named `*.min.js.gz`. Is it possible to have them in the format `*.min.js.gzip`?

**Comment by pakhuta** [comment]
Hi @bennyn,
Sorry for so long resolving issue. In v.1.0.0 was added possibility to specify extension of output files. Now you can use `gzip dist/*.* -e gzip` to achieve desired result. Enjoy!
