### ISSUE TITLE
Suggestion: better keywords and description

### ISSUE THREAD

**Issue by Buzut** [pakhuta/gzip-cli#13]
I was looking for a cli for Brotli and ended up finding you module when searching for a gzip-cli.

In my opinion, you should add "brotli-cli" as a keyword in the `package.json` and update the `package.json` description with the one you put on the Github repo:

> gzip-cli provides CLI for compressing files by using compress algorithms such as Gzip and Brotli.

Thanks for this awesome module!

**Comment by pakhuta** [comment]
Thanks for advice, I'll add it soon.
