### ISSUE TITLE
Add exclude directory

### ISSUE THREAD

**Issue by Buzut** [pakhuta/gzip-cli#14]
Glob is awesome, but it would be really a plus to be able to exclude directories. For instance, if there's a `node_module` in the directory I'm matching the files, I might want to exclude it.

As a workaround, what could also work is to accepting files as stdin. So that one could use the `find` command for advanced matching and pass the result to `gzip-cli`.

**Comment by pakhuta** [comment]
Hi @Buzut ,
I will take a look towards the end of the week. I guess I will use `ignore` option of `glob` package.
Thanks

**Comment by Buzut** [comment]
Awesome, thank you!

**Comment by pakhuta** [comment]
@Buzut , I have published beta version `1.2.0-beta.0`
Now is possible to specify array of glob patterns to exclude matches, for example:

CLI:
```
gzip source/**/*.js --ignore=source/node_modules/**
```

If `gzip` imported as a module:
```
gzip({patterns: ['dist/public/**/*.{html,css,js,svg}'], ignorePatterns: ['**/icons']});
``` 

Could you please check it and give a feedback?

P.S. Possibly in CLI a pattern will need be wrapped in double quotes:
```
gzip source/**/*.js --ignore="source/node_modules/**"
```

**Comment by Buzut** [comment]
Hey!
I started to have a look at it but left my tests unfinished.
I'll get back to you Wednesday when I'll had have time to properly test it out.

Thank you very much!

**Comment by Buzut** [comment]
I installed the 1.2.0-beta.0 version from npm (confirmed by checking the package.json in my `node_modules`).
Unless I missed something, it doesn't seem to work for me.

```
"scripts": {
  …
  "compress:js": "gzip './**/*.js' --ignore='node_modules' --extension=gz --extension=br",

  // also tried
  "compress:js": "gzip './**/*.js' --ignore='./node_modules' --extension=gz --extension=br",
  …
}
```

It's actually going into `node_modules` and compressing every js file inside it.

**Comment by pakhuta** [comment]
Try this one:
```
"compress:js": "gzip './**/*.js' --ignore='./node_modules/**' --extension=gz --extension=br",
```

**Comment by Buzut** [comment]
This one works, thank you very much! It's totally fine now. I didn't know that glob worked this way.

**Comment by pakhuta** [comment]
Thank you for testing.
Package v.`1.2.0` has been released.
