### ISSUE TITLE
Gzip, nut keep original file

### ISSUE THREAD

**Issue by maxfahl** [pakhuta/gzip-cli#5]
As of right now, the library removes the original files when gzip-ing, is there a way to keep them?

**Comment by maxfahl** [comment]
The issue I had was with the gzip library in OSX, there's a name conflict on my system. OSX gzip would appear before your node library in the path, so I never ran your code. May want to think of this, renaming your executable to something else than gzip.

**Comment by pakhuta** [comment]
Hi @maxfahl! Thanks for using `gzip-cli` ☺️.
I can't reproduce described issue. Check attached video.
Also, please check that you use NodeJS > 12.

If issue still reproduced, please provide a minimum reproducible example.


[output.mp4.zip](https://github.com/pakhuta/gzip-cli/files/4254170/output.mp4.zip)
